/**
 * Anthropic Claude AI provider (FUTURE OPTION).
 *
 * Production note:
 * - When enabling Claude:
 *     1. Add ANTHROPIC_API_KEY (see config/env.ts).
 *     2. Set DEFAULT_AI_PROVIDER = 'claude' in config/app.ts (or select per
 *        request) and use the AI SDK with model `${AI_MODELS.claude}`.
 *     3. Replace placeholder returns with real model calls, validating output
 *        with the Zod schemas in lib/validations.
 * - Until then this mirrors the Gemini placeholder behavior so the UI is
 *   unaffected regardless of which provider is selected.
 */
import { AI_MODELS } from '@/config/app'
import { conceptRepository } from '@/db/repositories/concept-repository'
import { quizRepository } from '@/db/repositories/quiz-repository'
import { analyticsRepository } from '@/db/repositories/analytics-repository'
import type {
  AIProvider,
  KnowledgeGraph,
  QuizRequest,
  SummaryRequest,
} from '@/lib/services/ai/ai-provider'
import type {
  Concept,
  ExamReadiness,
  GapTopic,
  QuizQuestion,
  Recommendation,
  Summary,
} from '@/types'

export class ClaudeProvider implements AIProvider {
  readonly name = 'claude' as const
  private readonly model = AI_MODELS.claude

  async generateSummary(req: SummaryRequest): Promise<Summary> {
    // TODO(claude): call generateText with `${this.model}`.
    return {
      id: `sum_${req.documentId}`,
      documentId: req.documentId,
      subjectId: req.subjectId ?? '',
      content: req.content ?? 'Summary will be generated by Claude.',
      createdAt: new Date().toISOString(),
    }
  }

  async generateQuiz(_req: QuizRequest): Promise<QuizQuestion[]> {
    return quizRepository.findQuestions()
  }

  async extractConcepts(_documentId: string): Promise<Concept[]> {
    return conceptRepository.findAllConcepts()
  }

  async generateRecommendations(_userId: string): Promise<Recommendation> {
    return analyticsRepository.recommendations()
  }

  async detectLearningGaps(_userId: string): Promise<GapTopic[]> {
    return analyticsRepository.learningGaps()
  }

  async calculateExamReadiness(_userId: string): Promise<ExamReadiness[]> {
    return analyticsRepository.examReadiness()
  }

  async generateKnowledgeGraph(_userId: string): Promise<KnowledgeGraph> {
    return {
      concepts: conceptRepository.findAllConcepts(),
      connections: conceptRepository.findAllConnections(),
    }
  }
}
