/**
 * Gemini AI provider (PRIMARY / default).
 *
 * Production note:
 * - When connecting Gemini:
 *     1. Add GOOGLE_GENERATIVE_AI_API_KEY (see config/env.ts).
 *     2. Use the AI SDK with the Google provider, e.g.
 *          import { generateObject, generateText } from 'ai'
 *          model: 'google/gemini-1.5-pro'  (see config/app.ts AI_MODELS)
 *     3. Replace each placeholder return below with a real model call,
 *        validating structured output with the Zod schemas in lib/validations.
 * - Today every method returns deterministic data from the repositories so the
 *   existing UI renders identically without any network calls.
 */
import { AI_MODELS } from '@/config/app'
import { conceptRepository } from '@/db/repositories/concept-repository'
import { quizRepository } from '@/db/repositories/quiz-repository'
import { analyticsRepository } from '@/db/repositories/analytics-repository'
import type {
  AIProvider,
  KnowledgeGraph,
  QuizRequest,
  SummaryRequest,
} from '@/lib/services/ai/ai-provider'
import type {
  Concept,
  ExamReadiness,
  GapTopic,
  QuizQuestion,
  Recommendation,
  Summary,
} from '@/types'

export class GeminiProvider implements AIProvider {
  readonly name = 'gemini' as const
  private readonly model = AI_MODELS.gemini

  async generateSummary(req: SummaryRequest): Promise<Summary> {
    // TODO(gemini): call generateText with `${this.model}` to summarize content.
    return {
      id: `sum_${req.documentId}`,
      documentId: req.documentId,
      subjectId: req.subjectId,
      content: req.content ?? 'Summary will be generated by Gemini.',
      createdAt: new Date().toISOString(),
    }
  }

  async generateQuiz(_req: QuizRequest): Promise<QuizQuestion[]> {
    // TODO(gemini): call generateObject with the QuizQuestion schema.
    return quizRepository.findQuestions()
  }

  async extractConcepts(_documentId: string): Promise<Concept[]> {
    // TODO(gemini): extract concepts from the document text.
    return conceptRepository.findAllConcepts()
  }

  async generateRecommendations(_userId: string): Promise<Recommendation> {
    // TODO(gemini): produce personalized next-step recommendations.
    return analyticsRepository.recommendations()
  }

  async detectLearningGaps(_userId: string): Promise<GapTopic[]> {
    // TODO(gemini): infer learning gaps from mastery + coverage signals.
    return analyticsRepository.learningGaps()
  }

  async calculateExamReadiness(_userId: string): Promise<ExamReadiness[]> {
    // TODO(gemini): score exam readiness per subject.
    return analyticsRepository.examReadiness()
  }

  async generateKnowledgeGraph(_userId: string): Promise<KnowledgeGraph> {
    // TODO(gemini): synthesize the knowledge graph from concepts + documents.
    return {
      concepts: conceptRepository.findAllConcepts(),
      connections: conceptRepository.findAllConnections(),
    }
  }
}
