/**
 * Domain model: User
 *
 * Production note:
 * - Identity/auth is owned by Clerk. `id` maps to the Clerk user id.
 *   See lib/services/auth/* for the Clerk integration seam.
 * - Persisted profile fields live in Aurora PostgreSQL (`users` table).
 */
export interface User {
  id: string
  name: string
  email: string
  initials: string
  plan: string
  streak: number
  goal: string
}

/**
 * Domain model: Subject
 *
 * Production note:
 * - Stored in Aurora PostgreSQL (`subjects` table), scoped per user.
 * - `icon` is a presentation concern resolved on the client; the database
 *   stores an icon key (string) rather than a component reference.
 */
import type { LucideIcon } from 'lucide-react'

export type FileType = 'pdf' | 'note' | 'image' | 'presentation' | 'video'

export interface TopConcept {
  name: string
  strength: number
}

export interface Subject {
  id: string
  name: string
  description: string
  color: string
  icon: LucideIcon
  documents: number
  concepts: number
  mastery: number
  lastStudied: string
  summaries: number
  quizzes: number
  topConcepts: TopConcept[]
}

/**
 * Domain model: Document (a stored knowledge item)
 *
 * Production note:
 * - File bytes live in AWS S3; only metadata references are stored in the
 *   application/database layer. See lib/services/s3-service.ts.
 */
export interface Document {
  id: string
  title: string
  type: FileType
  subjectId: string
  subject: string
  size: string
  uploadedAt: string
  summarized: boolean
  concepts: number
  excerpt: string
}

/** Backwards-compatible alias used across the dashboard UI. */
export type KnowledgeItem = Document

export type ActivityType = 'upload' | 'quiz' | 'summary' | 'subject'

export interface Activity {
  id: string
  action: string
  target: string
  time: string
  type: ActivityType
}

/**
 * Domain model: Summary
 *
 * Production note:
 * - Generated by the AI provider (Gemini by default) and persisted in Aurora.
 */
export interface Summary {
  id: string
  documentId: string
  subjectId: string
  content: string
  createdAt: string
}

/**
 * Domain model: Quiz + attempts
 *
 * Production note:
 * - Questions are AI-generated; attempts are persisted per user in Aurora.
 */
export interface QuizQuestion {
  id: string
  question: string
  options: string[]
  answer: number
  explanation: string
}

export interface Quiz {
  id: string
  subjectId: string
  questions: QuizQuestion[]
  createdAt: string
}

export interface QuizAttempt {
  id: string
  quizId: string
  userId: string
  score: number
  total: number
  completedAt: string
}

/**
 * Domain model: Concept + connections (knowledge graph nodes/edges)
 */
export type ConceptStatus = 'core' | 'emerging' | 'weak' | 'connected'
export type ConceptDifficulty = 'foundational' | 'intermediate' | 'advanced'
export type ConceptGroup = 'subject' | 'core' | 'concept' | 'document'

export interface Concept {
  id: string
  label: string
  group: ConceptGroup
  subject?: string
  mastery?: number
  importance?: number
  frequency?: number
  status?: ConceptStatus
  difficulty?: ConceptDifficulty
  recent?: boolean
}

export interface ConceptConnection {
  source: string
  target: string
  strength?: number
}

/** Backwards-compatible alias used by the knowledge-graph UI. */
export type Edge = ConceptConnection

/**
 * Domain model: Recommendation (AI coach next-step suggestions)
 */
export type StudyPathStatus = 'done' | 'current' | 'next' | 'locked'

export interface StudyPathStep {
  label: string
  subject: string
  status: StudyPathStatus
}

export interface Recommendation {
  nextTopic: {
    mastered: string
    recommended: string
    subject: string
    reason: string
    confidence: number
  }
  weakAreas: { name: string; subject: string; confidence: number }[]
  knowledgeGaps: { subject: string; missing: string[] }[]
  studyPath: StudyPathStep[]
  examReadiness: {
    current: number
    potential: number
    hoursNeeded: number
    examName: string
  }
}

/**
 * Domain model: LearningGap
 */
export type GapStatus = 'mastered' | 'partial' | 'missing'

export interface GapTopic {
  name: string
  subject: string
  status: GapStatus
  progress: number
}

/**
 * Domain model: ExamReadiness
 */
export interface ExamReadiness {
  subject: string
  coverage: number
  accuracy: number
  consistency: number
  confidence: number
}

/**
 * Learning intelligence summary (derived analytics surfaced on the dashboard).
 */
export interface LearningIntelligence {
  mostStudied: { concept: string; subject: string; sessions: number }
  weakest: { concept: string; subject: string; mastery: number }
  fastestImproving: { subject: string; delta: number }
  consistency: number
  coverage: number
  aiConfidence: number
  weeklyInsights: string[]
}

/**
 * Aggregate admin analytics.
 */
export interface AdminStats {
  totalUsers: number
  totalDocuments: number
  totalConcepts: number
  activeToday: number
  userGrowth: { month: string; users: number }[]
  engagement: { feature: string; usage: number }[]
}

/** Time-series points used by dashboard charts. */
export interface KnowledgeGrowthPoint {
  month: string
  concepts: number
  documents: number
}

export interface StudyActivityPoint {
  day: string
  minutes: number
}

/**
 * Storage model: a file persisted in AWS S3 with only metadata kept locally.
 */
export interface StoredFile {
  key: string
  bucket: string
  url: string
  contentType: string
  size: number
  uploadedAt: string
}

export interface UploadedDocument {
  documentId: string
  file: StoredFile
  subjectId: string
}
